// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
// / await Firebase.initializeApp(
// /   options: DefaultFirebaseOptions.currentPlatform,
// / );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAFoXVoF6jKmw7vFYwkaaJSJpqsMj8WhA4',
    appId: '1:1064457503986:web:63c4e9974dab5ea0573c6b',
    messagingSenderId: '1064457503986',
    projectId: 'sleeper-409912',
    authDomain: 'sleeper-409912.firebaseapp.com',
    databaseURL: 'https://sleeper-409912-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleeper-409912.appspot.com',
    measurementId: 'G-VBY2CKZB7G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfjTOeFYQD15OZPohu7e9EHyA-upwkKl8',
    appId: '1:1064457503986:android:f9ed02ce929ea121573c6b',
    messagingSenderId: '1064457503986',
    projectId: 'sleeper-409912',
    databaseURL: 'https://sleeper-409912-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleeper-409912.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZyZfQBNamYyoeWX045eliG3mXn2bBVhg',
    appId: '1:1064457503986:ios:b35089ac18ed0780573c6b',
    messagingSenderId: '1064457503986',
    projectId: 'sleeper-409912',
    databaseURL: 'https://sleeper-409912-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleeper-409912.appspot.com',
    iosBundleId: 'com.example.sleeperFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZyZfQBNamYyoeWX045eliG3mXn2bBVhg',
    appId: '1:1064457503986:ios:47ca94e3ddb16ff8573c6b',
    messagingSenderId: '1064457503986',
    projectId: 'sleeper-409912',
    databaseURL: 'https://sleeper-409912-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'sleeper-409912.appspot.com',
    iosBundleId: 'com.example.sleeperFlutter.RunnerTests',
  );
}
